[keys.alice]
path = "keys/alice.pub"
key_type = "rsa"

[keys.bob]
path = "keys/bob.pub"
key_type = "rsa"

[[steps]]
name = "clone"
expected_products = ["CREATE *"]
pubkeys = ["alice", "bob"]

[[steps]]
name = "update"
expected_materials = [
    "MATCH src/* WITH PRODUCTS FROM clone",
    "MATCH pyproject.toml WITH PRODUCTS FROM clone",
    "ALLOW README.md",
    "DISALLOW *",
]
expected_products = [
    "MODIFY pyproject.toml",
    "MODIFY src/main.py",
    "MATCH * WITH MATERIALS FROM update",
    "ALLOW README.md",
    "DISALLOW *",
]
pubkeys = ["alice", "bob"]

[[steps]]
name = "build"
expected_materials = [
    "MATCH src/* WITH PRODUCTS FROM update",
    "MATCH pyproject.toml WITH PRODUCTS FROM update",
    "ALLOW README.md",
    "DISALLOW *",
]
expected_products = [
    "CREATE *-*-py3-none-any.whl",
    "DISALLOW *",
]
pubkeys = ["alice"]

[[inspect]]
name = "unzip"
run = "unzip *-*-py3-none-any.whl"
expected_materials = [
    "MATCH *-*-py3-none-any.whl with PRODUCTS from build",
    "ALLOW *.layout",
    "ALLOW *.pub",
    "DISALLOW *",
]
expected_products = [
    "MATCH *.py WITH MATERIALS in src/ FROM build",
    "MATCH *-*-py3-none-any.whl with MATERIALS FROM unzip",
    "ALLOW *-*.dist-info/*",
    "ALLOW *.layout",
    "ALLOW *.pub",
    "DISALLOW *",
]
