[keys.alice]
path = "keys/alice.pub"
key_type = "rsa"

[[steps]]
name = "create"
expected_products = ["CREATE *"]
pubkeys = ["alice"]

[[steps]]
name = "build"
expected_materials = [
    "MATCH src/* WITH PRODUCTS FROM create",
    "MATCH pyproject.toml WITH PRODUCTS FROM create",
    "ALLOW README.md",
    "DISALLOW *",
]
expected_products = [
    "CREATE *-*-py3-none-any.whl",
    "DISALLOW *",
]
pubkeys = ["alice"]

[[inspect]]
name = "unzip"
run = "unzip *-*-py3-none-any.whl"
expected_materials = [
    "MATCH *-*-py3-none-any.whl WITH PRODUCTS FROM build",
    "ALLOW *.layout",
    "ALLOW *.pub",
    "DISALLOW *",
]
expected_products = [
    "MATCH *.py WITH MATERIALS IN src/ FROM build",
    "MATCH *-*-py3-none-any.whl WITH MATERIALS FROM unzip",
    "ALLOW *-*.dist-info/*",
    "ALLOW *.layout",
    "ALLOW *.pub",
    "DISALLOW *",
]
